---
- hosts: db-server
  gather_facts: no
  become_user: root
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx
        state=latest
      become: yes
    - name: start nginx
      service:
        name: nginx
        state: started
      become: yes

