---
- hosts: db-server
  gather_facts: no
  become_user: root
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx
        state=latest
      become: yes
    - name: start nginx
      service:
        name: nginx
        state: started
      become: yes
    - name: copy the nginx config file
      copy:
        src: /home/ubuntu/ansible-deploy/load-balancer.conf
        dest: /etc/nginx/sites-enabled/load-balancer.conf
      become: yes
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes
    - name: Install docker and dependencies
      apt:
        name: docker-ce, docker-ce-cli, containerd.io
        state: present
    - name: Start docker
      service:
        name: docker
        state: started
    - name: Install docker python module
      pip:
        name: docker
    - name: Create MySQL container
      docker_container:
        name: maria-db
        image: docker.io/bitnami/mariadb:10.3
        state: started
        recreate: yes
        env: 
          MARIADB_USER=user
          MARIADB_DATABASE=db
          ALLOW_EMPTY_PASSWORD=yes
        ports:
          - "3306:3306"
        volumes:
          - mariadb_data:/bitnami/mariadb
