---
- hosts: loadbalancer-db
  gather_facts: no
  become_user: root
  become: yes
  tasks:
    - name: Clone a github repository
      git:
        repo: https://github.com/mbiskho/PacilOps.git
        dest: /home/bisma/repos/
        clone: yes
        update: yes
    - name: "apt-get update"
      apt:
        update_cache: yes
        cache_valid_time: 3600    
    - name: "install nginx"
      apt:
        name: ['nginx']
        state: latest
    - name: delete default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx
    - name: Copy new nginx configuration
      become: true
      copy: 
        src: /home/bisma/repos/Delivery/Two/nginx/profile-1/
        dest: /etc/nginx/sites-available/
        mode: +rwx 
      notify: restart nginx
    - name: Install docker and dependencies
      apt:
        name: docker-ce, docker-ce-cli, containerd.io
        state: present
    - name: Start docker
      service:
        name: docker
        state: started
    - name: Create WordPress container
      docker_container:
        name: wordpress
        image: docker.io/bitnami/wordpress:latest
        state: started
        recreate: yes
        env: MARIADB_HOST=34.129.144.8
          MARIADB_PORT_NUMBER=3306
          WORDPRESS_DATABASE_USER=bn_wordpress
          WORDPRESS_DATABASE_NAME=bitnami_wordpress
          ALLOW_EMPTY_PASSWORD=yes
        ports:
          - "8000:8080"
          - "443:8443"
        volumes:
          - "wordpress_data:/bitnami/wordpress"
    - name: install zabbix-agent
      apt:
        name: zabbix-agent
        state: latest
        update_cache: yes
      when: ansible_distribution_release == 'jessie'
    - name: copy zabbix configuration file
      copy: src=./conf/zabbix_agentd.conf dest=/etc/zabbix_agentd.conf seuser=system_u
      notify:
        - Start Zabbix-agent
  
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
    - name: Start zabbix-agent
      service: name=zabbix-agent state=started enabled=yes


- hosts: file-app
  gather_facts: no
  become_user: root
  become: yes
  tasks:
    - name: Log into gitlab registry
      command: docker login {{ gitlab_registry }} -u {{ gitlab_user }} -p {{ gitlab_password }}
      no_log: true

    - name: Pull docker images
      command: docker-compose pull {{ docker_service }}
      args:
        chdir: "{{ docker_compose_path }}"

    - name: Log out of any docker registry
      command: docker logout
      no_log: true

    - name: Deploy services
      command: docker-compose up -d {{ docker_service }}
      args:
        chdir: "{{ docker_compose_path }}"

    - name: Remove old image
      command: docker image prune -a -f
    
    - name: install zabbix-agent
      apt:
        name: zabbix-agent
        state: latest
        update_cache: yes
      when: ansible_distribution_release == 'jessie'
    - name: copy zabbix configuration file
      copy: src=./conf/zabbix_agentd.conf dest=/etc/zabbix_agentd.conf seuser=system_u
      notify:
        - Start Zabbix-agent

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
    - name: Start zabbix-agent
      service: name=zabbix-agent state=started enabled=yes

- hosts: web-profile-app
  gather_facts: no
  remote_user: root
  become: yes
  tasks:
    - name: Install docker and dependencies
      apt:
        name: docker-ce, docker-ce-cli, containerd.io
        state: present
    - name: Start docker
      service:
        name: docker
        state: started
    - name: Install docker python module
      pip:
        name: docker
    - name: Create WordPress container
      docker_container:
        name: wordpress
        image: docker.io/bitnami/wordpress:latest
        state: started
        recreate: yes
        env: MARIADB_HOST=34.129.144.8
          MARIADB_PORT_NUMBER=3306
          WORDPRESS_DATABASE_USER=bn_wordpress
          WORDPRESS_DATABASE_NAME=bitnami_wordpress
          ALLOW_EMPTY_PASSWORD=yes
        ports:
          - "8000:8080"
          - "443:8443"
        volumes:
          - "wordpress_data:/bitnami/wordpress"
          - name: Create Zabbix Agent Monitor Server
      docker_container:
        name: zabbix-agent-cms-1
        image: zabbix/zabbix-agent:ubuntu-5.2-latest
        state: started
        privileged: true
        recreate: yes
        env:
          ZBX_HOSTNAME="Zabbix server"
          ZBX_SERVER_HOST=172.31.17.132
        pid_mode: host
        network_mode: host
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./zbx_env/etc/zabbix/zabbix_agentd.d:/etc/zabbix/zabbix_agentd.d:ro
          - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
          - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
          - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro /:/rootfs
          - /var/run:/var/run

- hosts: moddle-app
  gather_facts: no
  become_user: root
  become: yes
  tasks:
    - name: Create a k8s namespace
      k8s:
        name: ata-namespace #
        api_version: v1
        kind: Namespace
        state: present    

    - name: copying file with playbook
      become: true
      copy:
        src: /home/ubuntu/ansible_k8s_module_demo/pod.yaml
        dest: /tmp/pod.yaml

    - name: copying file with playbook
      become: true
      copy:
        src: /home/ubuntu/ansible_k8s_module_demo/deployment.yaml
        dest: /tmp/deployment.yaml


    - name: Create a pod
      k8s:
        state: present      
        namespace: ata-namespace  
        src: /tmp/pod.yaml


    - name: Get an existing Pods in the kubernetes cluster
      k8s:
        api_version: v1
        kind: pod
        name: nginx
        namespace: ata-namespace  
      register: web_service


    - name: Create a deployment
      k8s:
        state: present            
        namespace: ata-namespace  
        src: /tmp/deployment.yaml 

    - name: install zabbix-agent
      apt:
        name: zabbix-agent
        state: latest
        update_cache: yes
      when: ansible_distribution_release == 'jessie'

    - name: copy zabbix configuration file
      copy: src=./conf/zabbix_agentd.conf dest=/etc/zabbix_agentd.conf seuser=system_u
      notify:
        - Start Zabbix-agent

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
    - name: Start zabbix-agent
      service: name=zabbix-agent state=started enabled=yes

- hosts: zabbix-monitor
  gather_facts: no
  become_user: root
  become: yes
  tasks:
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
    - name: Start docker
      service:
        name: docker
        state: started
    - name: "apt-get update"
      apt:
        update_cache: yes
        cache_valid_time: 3600    
    - name: "install pip"
      apt:
        name: ['python-pip','python3-pip']
        state: latest
    - name: Install docker python module
      pip:
        name: docker
    - name: Create MySQL container
      docker_container:
        name: maria-db
        image: docker.io/bitnami/mariadb:10.3
        state: started
        recreate: yes
        env:
          MARIADB_USER=zabbix
          MARIADB_DATABASE=zabbix
          MARIADB_PASSWORD=zabbix
          MARIADB_ROOT_PASSWORD=zabbix
        ports:
          - "3306:3306"
        volumes:
          - mariadb_data:/bitnami/mariadb
    - name: Create Zabbix Server Container
      docker_container:
        name: zabbix-server-mysql
        image: zabbix/zabbix-server-mysql:ubuntu-5.2-latest
        state: started
        recreate: yes
        env:
          DB_SERVER_HOST=34.136.196.143
          DB_SERVER_PORT=3306
          MYSQL_USER=zabbix
          MYSQL_PASSWORD=zabbix
          MYSQL_ROOT_PASSWORD=zabbix
        network_mode: host
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
          - ./zbx_env/usr/lib/zabbix/externalscripts:/usr/lib/zabbix/externalscripts:ro
          - ./zbx_env/var/lib/zabbix/export:/var/lib/zabbix/export:rw
          - ./zbx_env/var/lib/zabbix/modules:/var/lib/zabbix/modules:ro
          - ./zbx_env/var/lib/zabbix/enc:/var/lib/zabbix/enc:ro
          - ./zbx_env/var/lib/zabbix/ssh_keys:/var/lib/zabbix/ssh_keys:ro
          - ./zbx_env/var/lib/zabbix/mibs:/var/lib/zabbix/mibs:ro
          - snmptraps:/var/lib/zabbix/snmptraps:rw