version: '3.3'
services:
  service-db:
      image: mysql:8.0.26
      container_name: mysql-local
      restart: always
      deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=pacilops
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
      ports:
        - 3306:3306
      expose:
        - '3306'
      volumes:
        - service-db:/var/lib/mysql
volumes:
  service-db:
