---
all:
  children:
    db-server:
      hosts: 
        34.134.11.200:
      vars:
        mysql_root_pass: pacilops
        mysql_db: db
        mysql_user: user
        mysql_pass: pass
    # zabbix-server:
    #   hosts: 34.136.196.143